### ISSUE TITLE
Switching between events sometimes moves session data

### ISSUE THREAD

**Issue by notkevin888** [jfly/tnt#7]
For example, if I'm currently in a 7x7 session, and I switch to 3x3, sometimes the session data for 7x7 gets moved into 3x3.  I haven't been able to figure out when and why it does it consistently.

**Comment by jfly** [comment]
Haha, if you look at the dropdowns carefully, you'll see that there are 2 arrows. The behavior of the 2 arrows is different =). Terrible idea, but that's how it works =)

**Comment by notkevin888** [comment]
Ohh, okay.  It'd be nice to have some documentation on what those do somewhere :P
